/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ce272286-acc5-4f5e-8204-99db523ff4e2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_IOlrhoBn4",
    "aws_user_pools_web_client_id": "1rfpm3m42lgsn705nmg198rid",
    "oauth": {
        "domain": "vnspocc71e6973-c71e6973-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
