/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region"          : "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:03e3be68-46f3-494d-bf92-56febef3ecb6",
    "aws_cognito_region"          : "us-east-1",
    "aws_user_pools_id"           : "us-east-1_2DLkXRo2D",
    "aws_user_pools_web_client_id": "66jcp2sq7a1urv269bscmf7u9o",
    "oauth"                       : {}
};


export default awsmobile;
